### PR TITLE
Allow service registration from within

### PR DESCRIPTION
**Pull request by easeq**

### CODE REVIEW

**Comment by fho** [comment]
@easeq thanks a lot for you PR.
Unfortunately I have to decline it.
Providing and maintaining functionality to register services in consul is not scope of this project.
We want to keep the scope limited to providing a grpc consul resolver

**Comment by easeq** [comment]
@fho Thanks! I understand. Would it be alright with you if I maintain this in my fork?

**Comment by fho** [comment]
@easeq Yes, would be great.

I would recommend to move the functionality  also to a separate package in your fork or alternatively make it a standalone go-module.
It's functionality is independent from resolving consul services for GRPC clients.
It will be also useful in scenarios where a grpc consul resolver is not needed.
Having it in a separate package would also allows to import the registrator package without getting  indirectly the dependency to the grpc package.

**Comment by easeq** [comment]
@fho Thanks, but for now I'll maintain it as a separate package with both the registrar and resolver for my use-cases.

**Pull request closed without merging**
